### ISSUE TITLE
The program does not show all images

### ISSUE THREAD

**Issue by VanTuz5** [FaultierSP/civitaiapiclient#1]
The program shows only 100 images, although the author has more than 1000

**Comment by FaultierSP** [comment]
Hi,

thanks for the feedback! Yes, these are the current limitations of the official API. I will implement a "load more" button in few weeks.

Any other issues on your system? Does the app what it supposed to? :)

**Comment by FaultierSP** [comment]
Added the "load more" button to the v0.0.2.

Thank you for contributing.
