### ISSUE TITLE
(Request) Bulk download all images from user

### ISSUE THREAD

**Issue by AldebaraanMKII** [FaultierSP/civitaiapiclient#3]
I know that you're going to implement a feature to load more than one page, but would you be willing to add a button to download all images from a user in bulk? There's several users with over 10k images and it would be tiresome having to load over 100 pages 1 by 1.

**Comment by FaultierSP** [comment]
There is a limit for the returned images by the API. So I'm thinking, how this function should look like. Should it be a separate page or somehow integrated in the image search section?

**Comment by AldebaraanMKII** [comment]
> There is a limit for the returned images by the API. So I'm thinking, how this function should look like. Should it be a separate page or somehow integrated in the image search section?

Something like the "load more" button but that goes through all pages of that user and downloads everything in bulk. So if a user has 10k images, it will go through each of the 100 pages and download everything in it. This way a user does not need to select all images in a page, download them, then press the load more button and repeat this process 100 times.

**Comment by FaultierSP** [comment]
Got it. Please check the latest version.

https://github.com/FaultierSP/civitaiapiclient/releases/tag/v0.0.3

As I said, because the limitations of the API it has to be a multi-step process. That's why it is in a separate menu item.

Thanks for contributing.
