### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by VanTuz5** [FaultierSP/civitaiapiclient#4]
When I try to find and download all the Batatavoadora's works, it shows this error
![image](https://github.com/user-attachments/assets/3fdf0ac3-8e5f-4fd1-85f5-5302fb71c91f)

**Comment by FaultierSP** [comment]
Couldn't really replicate, maybe it was an API hiccup. However, I've changed the way the JSON is getting serialized.

Please check the latest version and give a short feedback, is the issue is resolved.
https://github.com/FaultierSP/civitaiapiclient/releases/tag/v0.0.4

**Comment by VanTuz5** [comment]
Yes, it helped
