### ISSUE TITLE
(Request) Portability

### ISSUE THREAD

**Issue by AldebaraanMKII** [FaultierSP/civitaiapiclient#5]
The app in the current version saves its setting in the appdata folder. Would it be possible to make it create the file in the same directory as the program for better portability?

btw thanks a lot for making #3! It saves a lot of time.

**Comment by FaultierSP** [comment]
Yeah, sure, why not.

It will take a week or two though, my vacation is almost over. :)

**Comment by FaultierSP** [comment]
Done. Please check the latest version.

https://github.com/FaultierSP/civitaiapiclient/releases/tag/v0.0.5

Note that since the configuration file moved to the app's folder, you may want to check your settings again and delete old files in your system's default folder.
