### ISSUE TITLE
Programm don't search anything

### ISSUE THREAD

**Issue by VanTuz5** [FaultierSP/civitaiapiclient#7]
"Download all creator's images" has stopped working.

**Comment by FaultierSP** [comment]
Welp, as it seems, Civitai changed it's API response. :) It doesn't give back all images either. I will need a day or two to fix it.

Thanks for the heads-up.

**Comment by FaultierSP** [comment]
Done. Please check the latest version.

https://github.com/FaultierSP/civitaiapiclient/releases/tag/v0.0.5

Note that since the configuration file moved to the app's folder, you may want to check your settings again and delete old files in your system's default folder.
